### ISSUE TITLE
Scenic.Driver.Glfw can't be found when run mix scenic.run

### ISSUE THREAD

**Issue by ray-sh** [ScenicFramework/scenic#164]
### Versions and Environment
elixir -v
Erlang/OTP 21 [erts-10.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.8.1 (compiled with Erlang/OTP 21)

```

Scenic:

mix deps | grep scenic
* scenic_sensor 0.7.0 (Hex package) (mix)
  locked at 0.7.0 (scenic_sensor) a12aed75
* scenic 0.10.2 (Hex package) (mix)
  locked at 0.10.2 (scenic) f4f0a00e
* scenic_clock 0.10.0 (Hex package) (mix)
  locked at 0.10.0 (scenic_clock) 5be4a87e

OS:
Mac OS 10.13.4 (17E199)

### Steps to reproduce
https://github.com/boydm/scenic_new

### Actual Behavior

mix deps.get
Resolving Hex dependencies...
Dependency resolution completed:
New:
  elixir_make 0.6.0
  font_metrics 0.3.1
  msgpax 2.2.3
  scenic 0.10.2
  scenic_clock 0.10.0
  scenic_driver_glfw 0.10.0
  scenic_sensor 0.7.0
* Getting scenic (Hex package)
* Getting scenic_driver_glfw (Hex package)
* Getting scenic_sensor (Hex package)
* Getting scenic_clock (Hex package)
* Getting elixir_make (Hex package)
* Getting font_metrics (Hex package)
* Getting msgpax (Hex package)

mix scenic.run
==> msgpax
Compiling 8 files (.ex)
Generated msgpax app
==> font_metrics
Compiling 2 files (.ex)
Generated font_metrics app
==> scenic_sensor
Compiling 1 file (.ex)
Generated scenic_sensor app
==> elixir_make
Compiling 1 file (.ex)
Generated elixir_make app
==> scenic
mkdir -p /Users/xman/elixir-learning/my_app/_build/rpi3_dev/lib/scenic/ebin/../priv
cp -rf static /Users/xman/elixir-learning/my_app/_build/rpi3_dev/lib/scenic/ebin/../priv/static
mkdir -p /Users/xman/elixir-learning/my_app/_build/rpi3_dev/lib/scenic/ebin/../obj
cc -c -I/usr/local/Cellar/erlang/21.3/lib/erlang/usr/include -fPIC -O2 -Wall -Wextra -Wno-unused-parameter -std=c99 -o /Users/xman/elixir-learning/my_app/_build/rpi3_dev/lib/scenic/ebin/../obj/line.o c_src/line.c
cc /Users/xman/elixir-learning/my_app/_build/rpi3_dev/lib/scenic/ebin/../obj/line.o -L/usr/local/Cellar/erlang/21.3/lib/erlang/usr/lib -fPIC -shared  -dynamiclib -undefined dynamic_lookup -o /Users/xman/elixir-learning/my_app/_build/rpi3_dev/lib/scenic/ebin/../priv/line.so
cc -c -I/usr/local/Cellar/erlang/21.3/lib/erlang/usr/include -fPIC -O2 -Wall -Wextra -Wno-unused-parameter -std=c99 -o /Users/xman/elixir-learning/my_app/_build/rpi3_dev/lib/scenic/ebin/../obj/matrix.o c_src/matrix.c
cc /Users/xman/elixir-learning/my_app/_build/rpi3_dev/lib/scenic/ebin/../obj/matrix.o -L/usr/local/Cellar/erlang/21.3/lib/erlang/usr/lib -fPIC -shared  -dynamiclib -undefined dynamic_lookup -o /Users/xman/elixir-learning/my_app/_build/rpi3_dev/lib/scenic/ebin/../priv/matrix.so
cc -c -I/usr/local/Cellar/erlang/21.3/lib/erlang/usr/include -fPIC -O2 -Wall -Wextra -Wno-unused-parameter -std=c99 -o /Users/xman/elixir-learning/my_app/_build/rpi3_dev/lib/scenic/ebin/../obj/texture.o c_src/texture.c
cc /Users/xman/elixir-learning/my_app/_build/rpi3_dev/lib/scenic/ebin/../obj/texture.o -L/usr/local/Cellar/erlang/21.3/lib/erlang/usr/lib -fPIC -shared  -dynamiclib -undefined dynamic_lookup -o /Users/xman/elixir-learning/my_app/_build/rpi3_dev/lib/scenic/ebin/../priv/texture.so
Compiling 91 files (.ex)
Generated scenic app
==> scenic_clock
Compiling 3 files (.ex)
Generated scenic_clock app
==> my_app
Compiling 11 files (.ex)
Generated my_app app
** (Mix) Could not start application my_app: MyApp.start(:normal, []) returned an error: shutdown: failed to start child: Scenic
    ** (EXIT) shutdown: failed to start child: Scenic.ViewPort.SupervisorTop
        ** (EXIT) shutdown: failed to start child: :main_viewport
            ** (EXIT) shutdown: failed to start child: Scenic.ViewPort.Driver.Supervisor
                ** (EXIT) an exception was raised:
                    ** (ArgumentError) The module Scenic.Driver.Glfw was given as a child to a supervisor but it does not exist.
                        (elixir) lib/supervisor.ex:629: Supervisor.init_child/1
                        (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
                        (elixir) lib/supervisor.ex:615: Supervisor.init/2
                        (stdlib) supervisor.erl:295: :supervisor.init/1
                        (stdlib) gen_server.erl:374: :gen_server.init_it/2
                        (stdlib) gen_server.erl:342: :gen_server.init_it/6
                        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3

**Comment by boydm** [comment]
This seems related to another discussion. possibly being built into the wrong place. Looking into it.

**Comment by axelson** [comment]
@ray-sh Can you recheck with scenic_driver_glfw 0.10.1 and scenci_new 0.10.3? I'd expect it to work with those versions.

**Comment by smedegaard** [comment]
To others that may have this kind of error: check if you have a `MIX_TARGET` set to for example `rpi3`. I blanked my `MIX_TARGET`. That solved it

**Comment by wilsonsilva** [comment]
I fixed this by installing `glfw3` and compiling `scenic_driver_glfw` manually:

```sh
brew update
brew install glfw3 glew pkg-config

mix deps.compile scenic_driver_glfw
mix do deps.get, scenic.run
```

**Comment by gabrielmancini** [comment]
i had the same issue here, my dev environment is a ubuntu.

```
➜  firmware git:(master) ✗ mix clean --all && mix deps.get && mix deps.compile   

==> nerves
==> firmware

Nerves environment
  MIX_TARGET:   rpi3
  MIX_ENV:      dev

Resolving Hex dependencies...
Dependency resolution completed:
Unchanged:
  beam_notify 0.2.1
  circuits_gpio 0.4.8
  circular_buffer 0.4.0
  cowboy 2.9.0
  cowlib 2.8.0
  elixir_make 0.6.2
  file_system 0.2.10
  font_metrics 0.3.1
  gen_state_machine 3.0.0
  gettext 0.18.2
  jason 1.2.2
  json 1.4.1
  mdns_lite 0.7.0
  mime 2.0.1
  msgpax 2.3.0
  muontrap 0.6.1
  nerves 1.7.11
  nerves_pack 0.4.2
  nerves_runtime 0.11.6
  nerves_ssh 0.2.2
  nerves_system_bbb 2.11.2
  nerves_system_br 1.16.4
  nerves_system_osd32mp1 0.7.2
  nerves_system_rpi 1.16.2
  nerves_system_rpi0 1.16.2
  nerves_system_rpi2 1.16.2
  nerves_system_rpi3 1.16.2
  nerves_system_rpi3a 1.16.2
  nerves_system_rpi4 1.16.2
  nerves_system_x86_64 1.16.2
  nerves_time 0.4.3
  nerves_toolchain_aarch64_nerves_linux_gnu 1.4.3
  nerves_toolchain_armv6_nerves_linux_gnueabihf 1.4.3
  nerves_toolchain_armv7_nerves_linux_gnueabihf 1.4.3
  nerves_toolchain_ctng 1.8.4
  nerves_toolchain_x86_64_nerves_linux_musl 1.4.3
  one_dhcpd 0.2.5
  phoenix 1.5.3
  phoenix_html 2.14.3
  phoenix_live_dashboard 0.2.10
  phoenix_live_reload 1.3.3
  phoenix_live_view 0.14.8
  phoenix_pubsub 2.0.0
  plug 1.12.1
  plug_cowboy 2.3.0
  plug_crypto 1.2.2
  ranch 1.8.0
  ring_logger 0.8.2
  scenic 0.10.5
  scenic_driver_glfw 0.10.1
  shoehorn 0.7.0
  snapex7 0.1.3
  ssh_subsystem_fwup 0.6.0
  system_registry 0.8.2
  telemetry 0.4.3
  telemetry_metrics 0.6.1
  telemetry_poller 0.5.1
  toolshed 0.2.23
  uboot_env 0.3.0
  vintage_net 0.10.5
  vintage_net_direct 0.10.1
  vintage_net_ethernet 0.10.2
  vintage_net_wifi 0.10.5
  vintage_net_wizard 0.4.6

Nerves environment
  MIX_TARGET:   rpi3
  MIX_ENV:      dev

==> nerves
==> firmware
Resolving Nerves artifacts...
  Cached nerves_system_rpi3
  Cached nerves_toolchain_armv7_nerves_linux_gnueabihf

==> nerves
==> firmware

Nerves environment
  MIX_TARGET:   rpi3
  MIX_ENV:      dev

===> Analyzing applications...
===> Compiling ranch
===> Analyzing applications...
===> Compiling telemetry
===> Analyzing applications...
===> Compiling telemetry_poller
==> circuits_gpio
"**** MIX_ENV set to [prod] ****"
"**** CIRCUITS_MIX_ENV set to [] ****"
==> nerves_runtime
==> snapex7
make: Nothing to be done for 'all'.
==> one_dhcpd
make: Nothing to be done for 'all'.
==> muontrap
==> beam_notify
==> vintage_net
==> vintage_net_wifi
===> Analyzing applications...
===> Compiling cowlib
===> Analyzing applications...
===> Compiling cowboy
==> nerves_time
==> phoenix_live_reload
Compiling 1 file (.ex)
==> scenic
make: Nothing to be done for 'all'.
==> scenic_driver_glfw
mkdir -p /home/barba/Development/rms/client/firmware/_build/rpi3_dev/lib/scenic_driver_glfw/priv/prod
/home/barba/.nerves/artifacts/nerves_toolchain_armv7_nerves_linux_gnueabihf-linux_x86_64-1.4.3/bin/armv7-nerves-linux-gnueabihf-gcc -O3 -std=c99 `pkg-config --static --cflags glfw3 glew` -fPIC -o /home/barba/Development/rms/client/firmware/_build/rpi3_dev/lib/scenic_driver_glfw/priv/prod/scenic_driver_glfw c_src/main.c c_src/comms.c c_src/nanovg/nanovg.c c_src/utils.c c_src/render_script.c c_src/tx.c --sysroot=/home/barba/.nerves/artifacts/nerves_system_rpi3-portable-1.16.2/staging `pkg-config --static --libs glfw3 glew` -lGL -lm -lrt
Package glfw3 was not found in the pkg-config search path.
Perhaps you should add the directory containing `glfw3.pc'
to the PKG_CONFIG_PATH environment variable
No package 'glfw3' found
Package glew was not found in the pkg-config search path.
Perhaps you should add the directory containing `glew.pc'
to the PKG_CONFIG_PATH environment variable
No package 'glew' found
Package glfw3 was not found in the pkg-config search path.
Perhaps you should add the directory containing `glfw3.pc'
to the PKG_CONFIG_PATH environment variable
No package 'glfw3' found
Package glew was not found in the pkg-config search path.
Perhaps you should add the directory containing `glew.pc'
to the PKG_CONFIG_PATH environment variable
No package 'glew' found
c_src/main.c:13:10: fatal error: GL/glew.h: No such file or directory
   13 | #include <GL/glew.h>
      |          ^~~~~~~~~~~
compilation terminated.
c_src/comms.c:10:10: fatal error: GLFW/glfw3.h: No such file or directory
   10 | #include <GLFW/glfw3.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
c_src/utils.c:9:10: fatal error: GL/glew.h: No such file or directory
    9 | #include <GL/glew.h>
      |          ^~~~~~~~~~~
compilation terminated.
c_src/render_script.c:11:10: fatal error: GLFW/glfw3.h: No such file or directory
   11 | #include <GLFW/glfw3.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
In file included from c_src/tx.c:13:
c_src/comms.h:14:10: fatal error: GLFW/glfw3.h: No such file or directory
   14 | #include <GLFW/glfw3.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
Makefile:45: recipe for target '/home/barba/Development/rms/client/firmware/_build/rpi3_dev/lib/scenic_driver_glfw/priv/prod/scenic_driver_glfw' failed
make: *** [/home/barba/Development/rms/client/firmware/_build/rpi3_dev/lib/scenic_driver_glfw/priv/prod/scenic_driver_glfw] Error 1
could not compile dependency :scenic_driver_glfw, "mix compile" failed. You can recompile this dependency with "mix deps.compile scenic_driver_glfw", update it with "mix deps.update scenic_driver_glfw" or clean it with "mix deps.clean scenic_driver_glfw"
==> firmware
** (Mix) Could not compile with "make" (exit status: 2).
You need to have gcc and make installed. If you are using
Ubuntu or any other Debian-based system, install the packages
"build-essential". Also install "erlang-dev" package if not
included in your Erlang/OTP version. If you're on Fedora, run
"dnf group install 'Development Tools'".

```
the requirements for ubuntu is
```
 sudo apt-get install pkgconf libglfw3 libglfw3-dev libglew2.0 libglew-dev

```
i am install this too:

```
sudo apt-get install pkg-config 
```

**Comment by crertel** [comment]
Closing out for now, since `scenic_driver_glfw` is deprecated in favor of `scenic_driver_local`. Lemme know if you're still running into a variant of this problem!
